### PR TITLE
Add cleanup functions

### PR DESCRIPTION
**Pull request by selama1**
Just adding cleanup functions for old currency_id

### CODE REVIEW

**Comment by aih** [comment]
What do we do if there's an error in the currency_id processing (e.g. we get an incorrect currency_id, or incorrect data type)? Can we check for and report an error?

**Comment by selama1** [comment]
I can check that currency_id is an integer, and greater than 0.

If we want to do more defensive programming, I can also check that it less than or equal to the last id in the currency table. It would require one more database access to query for the last currency_id, but it won't have any measurable impact of performance.

**Comment by aih** [comment]
Yes, I think that extra step is worth it, since we're separating the id between repos.

**Comment by selama1** [comment]
Added range check to currency_id

**Pull request merged**
